# Generated by Django 5.0.2 on 2024-02-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('bookno', models.IntegerField(primary_key=True, serialize=False)),
                ('authorname', models.CharField(max_length=50)),
                ('price', models.IntegerField(help_text='enter price')),
                ('qty', models.IntegerField()),
                ('bookname', models.CharField(max_length=50)),
            ],
        ),
    ]
